# GitHub Actions Workflow definition to automatically create a new release for each new Git tag

name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15'
      - name: Setup Helm
        uses: azure/setup-helm@v1.1
        with:
          version: 'v3.3.4'

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DM_BOT_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: v0.143.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Helm Chart
        uses: docker://quay.io/helmpack/chart-releaser:v1.0.0
        with:
          args: cr upload
        env:
          CR_OWNER: ${{ github.repository_owner }}
          CR_GIT_REPO: 'osiris'
          CR_COMMIT: ${{ github.sha }}
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Helm Charts Index Directory
        run: mkdir -p ./.cr-index
      - name: Update Helm Charts Index
        uses: docker://quay.io/helmpack/chart-releaser:v1.0.0
        with:
          args: cr index
        env:
          CR_CHARTS_REPO: 'https://dailymotion-oss.github.io/osiris/charts/'
          CR_OWNER: ${{ github.repository_owner }}
          CR_GIT_REPO: 'osiris'

      - name: Push Helm Charts Index
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.cr-index
          destination_dir: charts
          keep_files: true
          enable_jekyll: true
